services:
  backend:
    build: ./backend
    volumes:
      - .romcikapraca/backend:/app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  frontend:
    build: ./frontend
    volumes:
      - .romcikapraca/frontend:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    depends_on:
      - backend
    restart: unless-stopped
